### ISSUE TITLE
MSA generation failed

### ISSUE THREAD

**Issue by johnny-rodriguez** [patrickbryant1/AFProfile#9]
I am having trouble running the generate_msas.sh. script. I see some errors with certain packages. Can you recommend a fix?

/home/johnny/Documents/AFProfile/data/test/test.fasta
/home/johnny/.local/lib/python3.10/site-packages/Bio/Data/SCOPData.py:18: BiopythonDeprecationWarning: The 'Bio.Data.SCOPData' module will be deprecated in a future release of Biopython in favor of 'Bio.Data.PDBData.
  warnings.warn(
2024-01-17 14:51:14.695653: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2024-01-17 14:51:14.695699: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2024-01-17 14:51:14.695703: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2024-01-17 14:51:15.220231: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory
2024-01-17 14:51:15.220262: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1934] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
I0117 14:51:15.478192 139710644158464 templates.py:857] Using precomputed obsolete pdbs ./obsolete.txt.
I0117 14:51:15.478430 139710644158464 run_alphafold_msa_template_only.py:243] Using random seed 2186063265457982969 for the data pipeline
I0117 14:51:15.478512 139710644158464 run_alphafold_msa_template_only.py:140] Predicting test
I0117 14:51:15.478878 139710644158464 pipeline_multimer.py:213] Running monomer pipeline on chain A: test1
I0117 14:51:15.479053 139710644158464 jackhmmer.py:133] Launching subprocess "./hmmer-3.3.2/src/jackhmmer -o /dev/null -A /tmp/tmp7anoar32/output.sto --noali --F1 0.0005 --F2 5e-05 --F3 5e-07 --incE 0.0001 -E 0.0001 --cpu 8 -N 1 /tmp/tmp9s8eyh2j.fasta /home/johnny/Documents/alphafold-databases/uniref90/uniref90.fasta"
I0117 14:51:15.479332 139710644158464 utils.py:36] Started Jackhmmer (uniref90.fasta) query
I0117 14:51:15.483907 139710644158464 utils.py:40] Finished Jackhmmer (uniref90.fasta) query in 0.005 seconds
Traceback (most recent call last):
  File "/home/johnny/Documents/AFProfile/src/.//run_alphafold_msa_template_only.py", line 268, in <module>
    app.run(main)
  File "/home/johnny/.local/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/johnny/.local/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/johnny/Documents/AFProfile/src/.//run_alphafold_msa_template_only.py", line 248, in main
    get_features(
  File "/home/johnny/Documents/AFProfile/src/.//run_alphafold_msa_template_only.py", line 151, in get_features
    feature_dict = data_pipeline.process(
  File "/home/johnny/Documents/AFProfile/src/alphafold/data/pipeline_multimer.py", line 267, in process
    chain_features = self._process_single_chain(
  File "/home/johnny/Documents/AFProfile/src/alphafold/data/pipeline_multimer.py", line 215, in _process_single_chain
    chain_features = self._monomer_data_pipeline.process(
  File "/home/johnny/Documents/AFProfile/src/alphafold/data/pipeline.py", line 171, in process
    jackhmmer_uniref90_result = run_msa_tool(
  File "/home/johnny/Documents/AFProfile/src/alphafold/data/pipeline.py", line 95, in run_msa_tool
    result = msa_runner.query(input_fasta_path, max_sto_sequences)[0]  # pytype: disable=wrong-arg-count
  File "/home/johnny/Documents/AFProfile/src/alphafold/data/tools/jackhmmer.py", line 171, in query
    single_chunk_result = self._query_chunk(
  File "/home/johnny/Documents/AFProfile/src/alphafold/data/tools/jackhmmer.py", line 142, in _query_chunk
    raise RuntimeError(
RuntimeError: Jackhmmer failed
stderr:

Error: Parse failed (sequence file /tmp/tmp9s8eyh2j.fasta):
Line 2: illegal character :

**Comment by patrickbryant1** [comment]
Hi,

It appears that you have a space in your fasta file that the parser does not seem to handle. Please look through your input files and assure that there are no strange chars there.

Patrick
